openapi: 3.0.0
info:
  title: HuLink
  description: ''
  contact: {}
  version: '1.0'
servers:
  - url: 'http://localhost:3000/v1'
    variables: {}
paths:
  /user:
    post:
      summary: ユーザを作成する
      description: ''
      operationId: post-user
      parameters:
        - name: authorization
          in: header
          description: Bearer xxx
          style: simple
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserInput'
        required: false
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    required:
                      - user
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/CreateUserError'
      deprecated: false
    get:
      summary: ユーザを取得する
      description: ''
      operationId: get-user
      parameters:
        - name: authorization
          in: header
          description: Bearer xxx
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    required:
                      - user
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
                required:
                  - data
            application/xml:
              schema:
                type: object
                properties: {}
      deprecated: false
  /link-user:
    get:
      summary: リンクユーザを一覧取得する
      description: ''
      operationId: get-link-user
      parameters:
        - name: authorization
          in: header
          description: Bearer xxx
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    required:
                      - linkUsers
                    properties:
                      linkUsers:
                        type: array
                        items:
                          $ref: '#/components/schemas/LinkUser'
                required:
                  - data
      deprecated: false
    post:
      summary: リンクユーザを作成する
      description: ''
      operationId: post-link-user
      parameters:
        - name: authorization
          in: header
          description: Bearer xxx
          style: simple
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLinkUserInput'
        required: false
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      linkUser:
                        $ref: '#/components/schemas/LinkUser'
                    required:
                      - linkUser
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/CreateLinkUserError'
      deprecated: false
    put:
      summary: リンクユーザを更新する
      operationId: put-link-user
      responses:
        '200':
          description: OK
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: Bearer xxx
  /health:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required:
                  - status
      operationId: get-health
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        linkUsers:
          type: array
          items:
            $ref: '#/components/schemas/LinkUser'
      required:
        - id
        - name
    LinkUser:
      title: LinkUser
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        name:
          type: string
        weight:
          type: integer
          format: int32
        label:
          type: string
        sex:
          type: string
      required:
        - id
        - userId
        - name
    CreateUserInput:
      title: CreateUserInput
      type: object
      properties:
        name:
          type: string
      required:
        - name
    CreateLinkUserInput:
      title: CreateLinkUserInput
      type: object
      properties:
        name:
          type: string
        interact:
          type: array
          items:
            type: string
        label:
          type: string
        sex:
          type: string
        userId:
          type: string
          format: uuid
      required:
        - name
        - interact
        - userId
    UpdateLinkUserInput:
      title: UpdateLinkUserInput
      type: object
      properties:
        name:
          type: string
        interact:
          type: array
          items:
            type: string
        label:
          type: string
        sex:
          type: string
        userId:
          type: string
          format: uuid
      required:
        - name
        - interact
        - userId
    400ValidationError:
      title: 400ValidationError
      type: object
      properties:
        code:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
              message:
                type: string
              errorcode:
                type: string
            required:
              - path
              - message
      required:
        - code
        - errors
    401Error:
      title: 401Error
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    500Error:
      title: 500Error
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    503Error:
      title: 503Error
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    Pagenation:
      title: Pagenation
      type: object
      properties:
        total:
          type: integer
    CreateUserError:
      title: CreateUserError
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    CreateLinkUserError:
      title: CreateLinkUserError
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    CreateLinkUserInput - copy:
      type: object
      properties:
        name:
          type: string
        userId:
          type: string
          format: uuid
        interact:
          type: array
          items:
            type: string
        label:
          type: string
        sex:
          type: string
      required:
        - name
        - userId
        - interact
  responses:
    '400':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/400ValidationError'
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/401Error'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/500Error'
    '503':
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/503Error'
  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: string
      description: Pagenation limit
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: string
      description: Pagenation offset
    authorization:
      name: authorization
      in: header
      required: false
      schema:
        type: string
      description: Bearer xxx
tags: []
