import { type FC, type ReactNode } from 'react'

import type { Metadata } from 'next'
import { KumaRegistry } from '@kuma-ui/next-plugin/registry'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <html lang="ja">
      <body>
        <KumaRegistry>{children}</KumaRegistry>
      </body>
    </html>
  )
}

export default RootLayout
