import { type FC, type ReactNode } from 'react'
import './global.css'

import type { Metadata } from 'next'
import { KumaRegistry } from '@kuma-ui/next-plugin/registry'

import { Header } from './components/Header'
import { Footer } from './components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <html lang="ja">
      <body>
        <Header />
        <KumaRegistry>{children}</KumaRegistry>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
