name: 'Checks'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run format check
        run: yarn format:check
      - name: Run lint
        run: yarn lint
